export const set12 = [
    { word: "brother" },
    { word: "father" },
    { word: "friend" },
    { word: "love" },
    { word: "mother" },
    { word: "picture" },
    { word: "been" },
    { word: "children" },
    { word: "month" },
    { word: "question" },
    { word: "their" },
    { word: "year" },
    { word: "before" },
    { word: "front" },
    { word: "heard" },
      //1
      { word: "the" },
      { word: "of" },
      { word: "and" },
      { word: "a" },
      { word: "to" },
      { word: "in" },
      { word: "is" },
      { word: "you" },
      { word: "that" },
      { word: "it" },
    //2
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //3
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //4
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //5
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //6
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //7
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //8
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //9
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //10
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
  ];