export const set6 = [
//1
  { word: "can't" },
  { word: "matter" },
  { word: "square" },
  { word: "syllables" },
  { word: "perhaps" },
  { word: "bill" },
  { word: "felt" },
  { word: "suddenly" },
  { word: "test" },
  { word: "direction" },
//2
  { word: "centers" },
  { word: "farmers" },
  { word: "ready" },
  { word: "anything" },
  { word: "divided" },
  { word: "general" },
  { word: "energy" },
  { word: "subject" },
  { word: "Europe" },
  { word: "moon" },
//3
  { word: "region" },
  { word: "return" },
  { word: "believe" },
  { word: "dance" },
  { word: "members" },
  { word: "picked" },
  { word: "simple" },
  { word: "cells" },
  { word: "paint" },
  { word: "mind" },
//4
  { word: "love" },
  { word: "cause" },
  { word: "rain" },
  { word: "exercise" },
  { word: "eggs" },
  { word: "train" },
  { word: "blue" },
  { word: "wish" },
  { word: "drop" },
  { word: "developed" },
//5
  { word: "window" },
  { word: "difference" },
  { word: "distance" },
  { word: "heart" },
  { word: "site" },
  { word: "sum" },
  { word: "summer" },
  { word: "wall" },
  { word: "forest" },
  { word: "probably" },
//6
  { word: "legs" },
  { word: "sat" },
  { word: "main" },
  { word: "winter" },
  { word: "wide" },
  { word: "written" },
  { word: "length" },
  { word: "reason" },
  { word: "kept" },
  { word: "interest" },
//7
  { word: "arms" },
  { word: "brother" },
  { word: "race" },
  { word: "present" },
  { word: "beautiful" },
  { word: "store" },
  { word: "job" },
  { word: "edge" },
  { word: "past" },
  { word: "sign" },
//8
  { word: "record" },
  { word: "finished" },
  { word: "discovered" },
  { word: "wild" },
  { word: "happy" },
  { word: "beside" },
  { word: "gone" },
  { word: "sky" },
  { word: "grass" },
  { word: "million" },
//9
  { word: "west" },
  { word: "lay" },
  { word: "weather" },
  { word: "root" },
  { word: "instruments" },
  { word: "meet" },
  { word: "third" },
  { word: "months" },
  { word: "paragraph" },
  { word: "raised" },
//10
  { word: "represent" },
  { word: "soft" },
  { word: "whether" },
  { word: "clohes" },
  { word: "flowers" },
  { word: "shall" },
  { word: "teacher" },
  { word: "held" },
  { word: "describe" },
  { word: "drive" },
];