export const set10 = [
//1
  { word: "company" },
  { word: "radio" },
  { word: "we'll" },
  { word: "action" },
  { word: "capital" },
  { word: "factories" },
  { word: "settled" },
  { word: "yellow" },
  { word: "isn't" },
  { word: "southern" },
//2
  { word: "truck" },
  { word: "fair" },
  { word: "printed" },
  { word: "wouldn't" },
  { word: "ahead" },
  { word: "chance" },
  { word: "born" },
  { word: "level" },
  { word: "triangle" },
  { word: "molecules" },
//3
  { word: "France" },
  { word: "repeated" },
  { word: "column" },
  { word: "western" },
  { word: "church" },
  { word: "sister" },
  { word: "oxygen" },
  { word: "plural" },
  { word: "various" },
  { word: "agree" },
//4
  { word: "opposite" },
  { word: "wrong" },
  { word: "chart" },
  { word: "prepared" },
  { word: "pretty" },
  { word: "solution" },
  { word: "fresh" },
  { word: "shop" },
  { word: "suffix" },
  { word: "especially" },
//5
  { word: "shoes" },
  { word: "actually" },
  { word: "nose" },
  { word: "afraid" },
  { word: "dead" },
  { word: "sugar" },
  { word: "adjective" },
  { word: "fig" },
  { word: "office" },
  { word: "huge" },
//6
  { word: "gun" },
  { word: "similar" },
  { word: "death" },
  { word: "score" },
  { word: "forward" },
  { word: "stretched" },
  { word: "experience" },
  { word: "rose" },
  { word: "allow" },
  { word: "fear" },
//7
  { word: "workers" },
  { word: "Washington" },
  { word: "Greek" },
  { word: "women" },
  { word: "bought" },
  { word: "led" },
  { word: "march" },
  { word: "northern" },
  { word: "create" },
  { word: "British" },
//8
  { word: "difficult" },
  { word: "match" },
  { word: "win" },
  { word: "doesn't" },
  { word: "steel" },
  { word: "total" },
  { word: "deal" },
  { word: "determine" },
  { word: "evening" },
  { word: "hoe" },
//9
  { word: "rope" },
  { word: "cotton" },
  { word: "apple" },
  { word: "details" },
  { word: "entire" },
  { word: "corn" },
  { word: "substances" },
  { word: "smell" },
  { word: "tools" },
  { word: "conditions" },
//10
  { word: "cows" },
  { word: "track" },
  { word: "arrived" },
  { word: "located" },
  { word: "sir" },
  { word: "seat" },
  { word: "division" },
  { word: "effect" },
  { word: "underline" },
  { word: "view" },
];