export const set5 = [
//1
  { word: "done" },
  { word: "English" },
  { word: "road" },
  { word: "half" },
  { word: "ten" },
  { word: "fly" },
  { word: "gave" },
  { word: "box" },
  { word: "finally" },
  { word: "wait" },
//2
  { word: "correct" },
  { word: "oh" },
  { word: "quickly" },
  { word: "person" },
  { word: "became" },
  { word: "shown" },
  { word: "minutes" },
  { word: "strong" },
  { word: "verb" },
  { word: "stars" },
//3
  { word: "front" },
  { word: "feel" },
  { word: "fact" },
  { word: "inches" },
  { word: "street" },
  { word: "he" },
  { word: "can" },
  { word: "go" },
  { word: "a" },
  { word: "this" },
//4
  { word: "I" },
  { word: "like" },
  { word: "do" },
  { word: "to" },
  { word: "you" },
  { word: "he" },
  { word: "can" },
  { word: "go" },
  { word: "a" },
  { word: "this" },
//5
  { word: "I" },
  { word: "like" },
  { word: "do" },
  { word: "to" },
  { word: "you" },
  { word: "he" },
  { word: "can" },
  { word: "go" },
  { word: "a" },
  { word: "this" },
//6
  { word: "I" },
  { word: "like" },
  { word: "do" },
  { word: "to" },
  { word: "you" },
  { word: "he" },
  { word: "can" },
  { word: "go" },
  { word: "a" },
  { word: "this" },
//7
  { word: "I" },
  { word: "like" },
  { word: "do" },
  { word: "to" },
  { word: "you" },
  { word: "he" },
  { word: "can" },
  { word: "go" },
  { word: "a" },
  { word: "this" },
//8
  { word: "I" },
  { word: "like" },
  { word: "do" },
  { word: "to" },
  { word: "you" },
  { word: "he" },
  { word: "can" },
  { word: "go" },
  { word: "a" },
  { word: "this" },
//9
  { word: "I" },
  { word: "like" },
  { word: "do" },
  { word: "to" },
  { word: "you" },
  { word: "he" },
  { word: "can" },
  { word: "go" },
  { word: "a" },
  { word: "this" },
//10
  { word: "I" },
  { word: "like" },
  { word: "do" },
  { word: "to" },
  { word: "you" },
  { word: "he" },
  { word: "can" },
  { word: "go" },
  { word: "a" },
  { word: "this" },
];