export const set7 = [
//1
  { word: "cross" },
  { word: "speak" },
  { word: "solve" },
  { word: "appear" },
  { word: "metal" },
  { word: "son" },
  { word: "either" },
  { word: "ice" },
  { word: "sleep" },
  { word: "village" },
//2
  { word: "factors" },
  { word: "result" },
  { word: "jumped" },
  { word: "snow" },
  { word: "ride" },
  { word: "care" },
  { word: "floor" },
  { word: "hill" },
  { word: "pushed" },
  { word: "baby" },
//3
  { word: "buy" },
  { word: "century" },
  { word: "outside" },
  { word: "everything" },
  { word: "tall" },
  { word: "already" },
  { word: "instead" },
  { word: "phrase" },
  { word: "soil" },
  { word: "bed" },
//4
  { word: "copy" },
  { word: "free" },
  { word: "hope" },
  { word: "spring" },
  { word: "case" },
  { word: "laughed" },
  { word: "nation" },
  { word: "quite" },
  { word: "type" },
  { word: "themselves" },
//5
  { word: "temperature" },
  { word: "bright" },
  { word: "lead" },
  { word: "everyone" },
  { word: "method" },
  { word: "section" },
  { word: "lake" },
  { word: "iron" },
  { word: "within" },
  { word: "dictionary" },
//6
  { word: "hair" },
  { word: "age" },
  { word: "amount" },
  { word: "scale" },
  { word: "pounds" },
  { word: "although" },
  { word: "per" },
  { word: "broken" },
  { word: "moment" },
  { word: "tiny" },
//7
  { word: "possible" },
  { word: "gold" },
  { word: "milk" },
  { word: "quiet" },
  { word: "natural" },
  { word: "lot" },
  { word: "stone" },
  { word: "act" },
  { word: "build" },
  { word: "middle" },
//8
  { word: "speed" },
  { word: "count" },
  { word: "consonant" },
  { word: "someone" },
  { word: "sail" },
  { word: "rolled" },
  { word: "bear" },
  { word: "wonder" },
  { word: "smiled" },
  { word: "angle" },
//9
  { word: "fraction" },
  { word: "Africa" },
  { word: "killed" },
  { word: "melody" },
  { word: "bottom" },
  { word: "trip" },
  { word: "hole" },
  { word: "poor" },
  { word: "let's" },
  { word: "fight" },
//10
  { word: "surprise" },
  { word: "French" },
  { word: "died" },
  { word: "beat" },
  { word: "exactly" },
  { word: "remain" },
  { word: "dress" },
  { word: "cat" },
  { word: "couldn't" },
  { word: "fingers" },
];