

export const set1 = [
    { word: "I" },
    { word: "like" },
    { word: "do" },
    { word: "to" },
    { word: "you" },
    { word: "he" },
    { word: "can" },
    { word: "go" },
    { word: "a" },
    { word: "this" },
    { word: "is" },
    { word: "my" },
    { word: "look" },
    { word: "little" },
    { word: "where" },
  ];
  
  // export const set2 = [
  //   { word: "play" },
  //   { word: "the" },
  //   { word: "we" },
  //   { word: "are" },
  //   { word: "me" },
  //   { word: "she" },
  //   { word: "with" },
  //   { word: "for" },
  //   { word: "and" },
  //   { word: "have" },
  //   { word: "see" },
  //   { word: "does" },
  //   { word: "not" },
  //   { word: "school" },
  //   { word: "what" },
  // ];
  
  export const set3 = [
    { word: "down" },
    { word: "out" },
    { word: "very" },
    { word: "up" },
    { word: "be" },
    { word: "come" },
    { word: "good" },
    { word: "pull" },
    { word: "fun" },
    { word: "make" },
    { word: "they" },
    { word: "too" },
    { word: "jump" },
    { word: "move" },
    { word: "run" },
  ];
  
  export const set4 = [
    { word: "two" },
    { word: "again" },
    { word: "help" },
    { word: "new" },
    { word: "there" },
    { word: "use" },
    { word: "could" },
    { word: "live" },
    { word: "one" },
    { word: "then" },
    { word: "three" },
    { word: "eat" },
    { word: "no" },
    { word: "of" },
    { word: "under" },
  ];
  
  export const set5 = [
    { word: "who" },
    { word: "all" },
    { word: "call" },
    { word: "day" },
    { word: "her" },
    { word: "want" },
    { word: "around" },
    { word: "by" },
    { word: "place" },
    { word: "many" },
    { word: "walk" },
    { word: "away" },
    { word: "now" },
    { word: "some" },
    { word: "today" },
  ];
  
  export const set6 = [
    { word: "way" },
    { word: "why" },
    { word: "green" },
    { word: "grow" },
    { word: "pretty" },
    { word: "should" },
    { word: "together" },
    { word: "water" },
    { word: "from" },
    { word: "any" },
    { word: "happy" },
    { word: "once" },
    { word: "ago" },
    { word: "boy" },
    { word: "girl" },
  ];
  
  export const set7 = [
    { word: "how" },
    { word: "old" },
    { word: "people" },
    { word: "after" },
    { word: "buy" },
    { word: "done" },
    { word: "every" },
    { word: "soon" },
    { word: "work" },
    { word: "about" },
    { word: "animal" },
    { word: "carry" },
    { word: "eight" },
    { word: "give" },
    { word: "our" },
  ];
  
  export const set8 = [
    { word: "blue" },
    { word: "into" },
    { word: "or" },
    { word: "because" },
    { word: "other" },
    { word: "small" },
    { word: "find" },
    { word: "food" },
    { word: "more" },
    { word: "over" },
    { word: "start" },
    { word: "warm" },
    { word: "caught" },
    { word: "flew" },
    { word: "know" },
  ];
  
  export const set9 = [
    { word: "laugh" },
    { word: "listen" },
    { word: "were" },
    { word: "found" },
    { word: "hard" },
    { word: "near" },
    { word: "woman" },
    { word: "would" },
    { word: "write" },
    { word: "four" },
    { word: "large" },
    { word: "none" },
    { word: "only" },
    { word: "put" },
    { word: "round" },
  ];
  
  export const set10 = [
    { word: "another" },
    { word: "climb" },
    { word: "full" },
    { word: "great" },
    { word: "poor" },
    { word: "began" },
    { word: "better" },
    { word: "guess" },
    { word: "learn" },
    { word: "through" },
    { word: "right" },
    { word: "sure" },
    { word: "color" },
    { word: "early" },
    { word: "instead" },
  ];
  
  export const set11 = [
    { word: "oh" },
    { word: "thought" },
    { word: "above" },
    { word: "nothing" },
    { word: "build" },
    { word: "fall" },
    { word: "knew" },
    { word: "money" },
    { word: "toward" },
    { word: "answer" },
    { word: "brought" },
    { word: "busy" },
    { word: "door" },
    { word: "enough" },
    { word: "eyes" },
  ];
  
  export const set12 = [
    { word: "brother" },
    { word: "father" },
    { word: "friend" },
    { word: "love" },
    { word: "mother" },
    { word: "picture" },
    { word: "been" },
    { word: "children" },
    { word: "month" },
    { word: "question" },
    { word: "their" },
    { word: "year" },
    { word: "before" },
    { word: "front" },
    { word: "heard" },
  ];
  
  export const set13 = [
    { word: "push" },
    { word: "tomorrow" },
    { word: "your" },
    { word: "favorite" },
    { word: "few" },
    { word: "gone" },
    { word: "surprise" },
    { word: "wonder" },
    { word: "young" },
  ];
