export const set13 = [
    { word: "push" },
    { word: "tomorrow" },
    { word: "your" },
    { word: "favorite" },
    { word: "few" },
    { word: "gone" },
    { word: "surprise" },
    { word: "wonder" },
    { word: "young" },
      //1
      { word: "the" },
      { word: "of" },
      { word: "and" },
      { word: "a" },
      { word: "to" },
      { word: "in" },
      { word: "is" },
      { word: "you" },
      { word: "that" },
      { word: "it" },
    //2
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //3
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //4
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //5
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //6
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //7
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //8
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //9
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
    //10
      { word: "I" },
      { word: "like" },
      { word: "do" },
      { word: "to" },
      { word: "you" },
      { word: "he" },
      { word: "can" },
      { word: "go" },
      { word: "a" },
      { word: "this" },
  ];