export const set4 = [
//1
  { word: "body" },
  { word: "music" },
  { word: "color" },
  { word: "stand" },
  { word: "sun" },
  { word: "questions" },
  { word: "fish" },
  { word: "area" },
  { word: "mark" },
  { word: "dog" },
//2
  { word: "horse" },
  { word: "birds" },
  { word: "problem" },
  { word: "complete" },
  { word: "room" },
  { word: "knew" },
  { word: "since" },
  { word: "every" },
  { word: "piece" },
  { word: "told" },
//3
  { word: "usually" },
  { word: "didn't" },
  { word: "friends" },
  { word: "easy" },
  { word: "heard" },
  { word: "order" },
  { word: "red" },
  { word: "door" },
  { word: "sure" },
  { word: "become" },
//4
  { word: "top" },
  { word: "ship" },
  { word: "across" },
  { word: "today" },
  { word: "during" },
  { word: "short" },
  { word: "better" },
  { word: "best" },
  { word: "however" },
  { word: "low" },
//5
  { word: "hours" },
  { word: "black" },
  { word: "products" },
  { word: "happened" },
  { word: "whole" },
  { word: "measure" },
  { word: "remember" },
  { word: "early" },
  { word: "waves" },
  { word: "reached" },
//6
  { word: "listen" },
  { word: "wind" },
  { word: "rock" },
  { word: "space" },
  { word: "covered" },
  { word: "fast" },
  { word: "several" },
  { word: "hold" },
  { word: "himself" },
  { word: "toward" },
//7
  { word: "five" },
  { word: "step" },
  { word: "morning" },
  { word: "passed" },
  { word: "vowel" },
  { word: "tru" },
  { word: "hundred" },
  { word: "against" },
  { word: "pattern" },
  { word: "numeral" },
//8
  { word: "table" },
  { word: "north" },
  { word: "slowly" },
  { word: "money" },
  { word: "map" },
  { word: "farm" },
  { word: "pulled" },
  { word: "draw" },
  { word: "voice" },
  { word: "seen" },
//9
  { word: "cold" },
  { word: "cried" },
  { word: "plan" },
  { word: "notice" },
  { word: "south" },
  { word: "sing" },
  { word: "war" },
  { word: "ground" },
  { word: "fall" },
  { word: "king" },
//10
  { word: "town" },
  { word: "I'll" },
  { word: "unit" },
  { word: "figure" },
  { word: "certain" },
  { word: "field" },
  { word: "travel" },
  { word: "wood" },
  { word: "fire" },
  { word: "upon" },
];