export const set5 = [
//1
  { word: "done" },
  { word: "English" },
  { word: "road" },
  { word: "half" },
  { word: "ten" },
  { word: "fly" },
  { word: "gave" },
  { word: "box" },
  { word: "finally" },
  { word: "wait" },
//2
  { word: "correct" },
  { word: "oh" },
  { word: "quickly" },
  { word: "person" },
  { word: "became" },
  { word: "shown" },
  { word: "minutes" },
  { word: "strong" },
  { word: "verb" },
  { word: "stars" },
//3
  { word: "front" },
  { word: "feel" },
  { word: "fact" },
  { word: "inches" },
  { word: "street" },
  { word: "decided" },
  { word: "contain" },
  { word: "course" },
  { word: "surface" },
  { word: "produce" },
//4
  { word: "building" },
  { word: "ocean" },
  { word: "class" },
  { word: "note" },
  { word: "nothing" },
  { word: "rest" },
  { word: "carefully" },
  { word: "scientists" },
  { word: "inside" },
  { word: "wheels" },
//5
  { word: "stay" },
  { word: "green" },
  { word: "known" },
  { word: "island" },
  { word: "week" },
  { word: "less" },
  { word: "machine" },
  { word: "base" },
  { word: "ago" },
  { word: "stood" },
//6
  { word: "plane" },
  { word: "system" },
  { word: "behind" },
  { word: "ran" },
  { word: "round" },
  { word: "boat" },
  { word: "game" },
  { word: "force" },
  { word: "brought" },
  { word: "understand" },
//7
  { word: "warm" },
  { word: "common" },
  { word: "bring" },
  { word: "explain" },
  { word: "dry" },
  { word: "though" },
  { word: "language" },
  { word: "shape" },
  { word: "deep" },
  { word: "thousands" },
//8
  { word: "yes" },
  { word: "clear" },
  { word: "equation" },
  { word: "yet" },
  { word: "government" },
  { word: "filled" },
  { word: "heat" },
  { word: "full" },
  { word: "hot" },
  { word: "check" },
//9
  { word: "object" },
  { word: "am" },
  { word: "rule" },
  { word: "among" },
  { word: "noun" },
  { word: "power" },
  { word: "cannot" },
  { word: "able" },
  { word: "six" },
  { word: "size" },
//10
  { word: "dark" },
  { word: "ball" },
  { word: "material" },
  { word: "special" },
  { word: "heavy" },
  { word: "fine" },
  { word: "pair" },
  { word: "circle" },
  { word: "include" },
  { word: "built" },
];