export const set8 = [
//1
  { word: "row" },
  { word: "least" },
  { word: "catch" },
  { word: "climbed" },
  { word: "wrote" },
  { word: "shouted" },
  { word: "continued" },
  { word: "itself" },
  { word: "else" },
  { word: "plains" },
//2
  { word: "gas" },
  { word: "England" },
  { word: "burning" },
  { word: "design" },
  { word: "joined" },
  { word: "foot" },
  { word: "law" },
  { word: "ears" },
  { word: "glass" },
  { word: "you're" },
//3
  { word: "grew" },
  { word: "skin" },
  { word: "valley" },
  { word: "cents" },
  { word: "key" },
  { word: "president" },
  { word: "brown" },
  { word: "trouble" },
  { word: "cool" },
  { word: "cloud" },
//4
  { word: "lost" },
  { word: "sent" },
  { word: "symbols" },
  { word: "wear" },
  { word: "bad" },
  { word: "save" },
  { word: "experiment" },
  { word: "engine" },
  { word: "alone" },
  { word: "drawing" },
//5
  { word: "east" },
  { word: "choose" },
  { word: "single" },
  { word: "touch" },
  { word: "information" },
  { word: "express" },
  { word: "mouth" },
  { word: "yard" },
  { word: "equal" },
  { word: "decimal" },
//6
  { word: "yourself" },
  { word: "control" },
  { word: "practice" },
  { word: "report" },
  { word: "straight" },
  { word: "rise" },
  { word: "statement" },
  { word: "stick" },
  { word: "party" },
  { word: "seeds" },
//7
  { word: "suppose" },
  { word: "woman" },
  { word: "coast" },
  { word: "bank" },
  { word: "period" },
  { word: "wire" },
  { word: "pay" },
  { word: "clean" },
  { word: "visit" },
  { word: "bit" },
//8
  { word: "whose" },
  { word: "received" },
  { word: "garden" },
  { word: "please" },
  { word: "strange" },
  { word: "caught" },
  { word: "fell" },
  { word: "team" },
  { word: "God" },
  { word: "captain" },
//9
  { word: "direct" },
  { word: "ring" },
  { word: "serve" },
  { word: "child" },
  { word: "desert" },
  { word: "increase" },
  { word: "history" },
  { word: "cost" },
  { word: "maybe" },
  { word: "business" },
//10
  { word: "separate" },
  { word: "break" },
  { word: "uncle" },
  { word: "hunting" },
  { word: "flow" },
  { word: "lady" },
  { word: "students" },
  { word: "human" },
  { word: "art" },
  { word: "feeling" },
];