export const set2 = [
//1
  { word: "over" },
  { word: "new" },
  { word: "sound" },
  { word: "take" },
  { word: "only" },
  { word: "little" },
  { word: "work" },
  { word: "know" },
  { word: "place" },
  { word: "years" },
//2
  { word: "live" },
  { word: "me" },
  { word: "back" },
  { word: "give" },
  { word: "most" },
  { word: "very" },
  { word: "after" },
  { word: "things" },
  { word: "our" },
  { word: "just" },
//3
  { word: "name" },
  { word: "good" },
  { word: "sentence" },
  { word: "man" },
  { word: "think" },
  { word: "say" },
  { word: "great" },
  { word: "where" },
  { word: "help" },
  { word: "through" },
//4
  { word: "much" },
  { word: "before" },
  { word: "line" },
  { word: "right" },
  { word: "too" },
  { word: "means" },
  { word: "old" },
  { word: "any" },
  { word: "same" },
  { word: "tell" },
//5
  { word: "boy" },
  { word: "follow" },
  { word: "came" },
  { word: "want" },
  { word: "show" },
  { word: "also" },
  { word: "around" },
  { word: "form" },
  { word: "three" },
  { word: "small" },
//6
  { word: "set" },
  { word: "put" },
  { word: "end" },
  { word: "does" },
  { word: "another" },
  { word: "well" },
  { word: "large" },
  { word: "must" },
  { word: "big" },
  { word: "even" },
//7
  { word: "such" },
  { word: "because" },
  { word: "turn" },
  { word: "here" },
  { word: "why" },
  { word: "ask" },
  { word: "went" },
  { word: "men" },
  { word: "read" },
  { word: "need" },
//8
  { word: "land" },
  { word: "different" },
  { word: "home" },
  { word: "us" },
  { word: "move" },
  { word: "try" },
  { word: "kind" },
  { word: "hand" },
  { word: "picture" },
  { word: "again" },
//9
  { word: "change" },
  { word: "off" },
  { word: "play" },
  { word: "spell" },
  { word: "air" },
  { word: "away" },
  { word: "animal" },
  { word: "house" },
  { word: "point" },
  { word: "page" },
//10
  { word: "letter" },
  { word: "mother" },
  { word: "answer" },
  { word: "found" },
  { word: "study" },
  { word: "still" },
  { word: "learn" },
  { word: "should" },
  { word: "America" },
  { word: "world" },
];