export const set9 = [
//1
  { word: "supply" },
  { word: "corner" },
  { word: "electric" },
  { word: "insects" },
  { word: "crops" },
  { word: "tone" },
  { word: "hit" },
  { word: "sand" },
  { word: "doctor" },
  { word: "provide" },
//2
  { word: "thus" },
  { word: "won't" },
  { word: "cook" },
  { word: "bones" },
  { word: "mall" },
  { word: "board" },
  { word: "modern" },
  { word: "compound" },
  { word: "mine" },
  { word: "wasn't" },
//3
  { word: "fit" },
  { word: "addition" },
  { word: "belong" },
  { word: "safe" },
  { word: "soldiers" },
  { word: "guess" },
  { word: "silent" },
  { word: "trade" },
  { word: "rather" },
  { word: "compare" },
//4
  { word: "crowd" },
  { word: "poem" },
  { word: "enjoy" },
  { word: "elements" },
  { word: "indicate" },
  { word: "except" },
  { word: "expect" },
  { word: "flat" },
  { word: "seven" },
  { word: "interesting" },
//5
  { word: "sense" },
  { word: "string" },
  { word: "blow" },
  { word: "famous" },
  { word: "value" },
  { word: "wings" },
  { word: "movement" },
  { word: "pole" },
  { word: "exciting" },
  { word: "branches" },
//6
  { word: "thick" },
  { word: "blood" },
  { word: "lie" },
  { word: "spot" },
  { word: "bell" },
  { word: "fun" },
  { word: "loud" },
  { word: "consider" },
  { word: "suggested" },
  { word: "thin" },
//7
  { word: "position" },
  { word: "entered" },
  { word: "fruit" },
  { word: "tied" },
  { word: "rich" },
  { word: "dollars" },
  { word: "sent" },
  { word: "sight" },
  { word: "chief" },
  { word: "Japanese" },
//8
  { word: "stream" },
  { word: "planets" },
  { word: "rhythm" },
  { word: "eight" },
  { word: "science" },
  { word: "major" },
  { word: "observe" },
  { word: "tube" },
  { word: "necessary" },
  { word: "weight" },
//9
  { word: "meat" },
  { word: "lifted" },
  { word: "process" },
  { word: "army" },
  { word: "hat" },
  { word: "property" },
  { word: "particular" },
  { word: "swim" },
  { word: "terms" },
  { word: "current" },
//10
  { word: "park" },
  { word: "sell" },
  { word: "shoulder" },
  { word: "industry" },
  { word: "wash" },
  { word: "block" },
  { word: "spread" },
  { word: "cattle" },
  { word: "wife" },
  { word: "sharp" },
];