export const set3 = [
//1
  { word: "high" },
  { word: "every" },
  { word: "near" },
  { word: "add" },
  { word: "food" },
  { word: "between" },
  { word: "own" },
  { word: "below" },
  { word: "country" },
  { word: "plant" },
//2
  { word: "last" },
  { word: "school" },
  { word: "father" },
  { word: "keep" },
  { word: "tree" },
  { word: "never" },
  { word: "start" },
  { word: "city" },
  { word: "earth" },
  { word: "eyes" },
//3
  { word: "light" },
  { word: "thought" },
  { word: "head" },
  { word: "under" },
  { word: "story" },
  { word: "saw" },
  { word: "left" },
  { word: "don't" },
  { word: "few" },
  { word: "while" },
//4
  { word: "along" },
  { word: "might" },
  { word: "close" },
  { word: "something" },
  { word: "seem" },
  { word: "next" },
  { word: "hard" },
  { word: "open" },
  { word: "example" },
  { word: "begin" },
//5
  { word: "life" },
  { word: "always" },
  { word: "those" },
  { word: "both" },
  { word: "paper" },
  { word: "together" },
  { word: "got" },
  { word: "group" },
  { word: "often" },
  { word: "run" },
//6
  { word: "important" },
  { word: "until" },
  { word: "children" },
  { word: "side" },
  { word: "feet" },
  { word: "car" },
  { word: "mile" },
  { word: "night" },
  { word: "walk" },
  { word: "white" },
//7
  { word: "sea" },
  { word: "began" },
  { word: "grow" },
  { word: "took" },
  { word: "river" },
  { word: "four" },
  { word: "carry" },
  { word: "state" },
  { word: "once" },
  { word: "book" },
//8
  { word: "hear" },
  { word: "stop" },
  { word: "without" },
  { word: "second" },
  { word: "late" },
  { word: "miss" },
  { word: "idea" },
  { word: "enough" },
  { word: "eat" },
  { word: "face" },
//9
  { word: "watch" },
  { word: "far" },
  { word: "Indian" },
  { word: "real" },
  { word: "almost" },
  { word: "let" },
  { word: "above" },
  { word: "girl" },
  { word: "sometimes" },
  { word: "mountains" },
//10
  { word: "cut" },
  { word: "young" },
  { word: "talk" },
  { word: "soon" },
  { word: "list" },
  { word: "song" },
  { word: "being" },
  { word: "leave" },
  { word: "family" },
  { word: "it's" },
];